name: cage
channels:
  - pytorch
  - pyg
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python~=3.10.12
  - pytorch~=2.0.1
  - pytorch-cuda~=11.7
  - diffusers~=0.18.2
  - pip:
    - lightning~=2.0.7
    - tensorboard~=2.14.0
    - pyrender~=0.1.45
    - networkx~=3.1
    - open3d~=0.16.0
    - trimesh~=3.23.5
    - plotly~=5.16.1
    - matplotlib~=3.7.2
    - imageio~=2.31.2
    - omegaconf~=2.3.0
    
